### PR TITLE
Punctioation Correction in README codeblock

### PR DESCRIPTION
**Pull request by welkerc**
Just changing a database name from band-sched to band_sched so that while following the readme.md an SQL error does not occur.

### CODE REVIEW

**Comment by vwbusguy** [comment]
Let's separate out the README update from the Dockerfile.  I certainly welcome a Docker hook, but let's handle them separately.

**Comment by vwbusguy** [comment]
db/fcc_worship.ini is problematic since this would expose those credentials to the world.  If credentials are to be in the app root, they need to be so in a way that cannot be deciphered by the end user - ie, in a PHP file that is generated by an install script.

**Comment by vwbusguy** [comment]
If you can send me the README file separately, I'll gladly merge it.

**Comment by welkerc** [comment]
this should be just the readme, I made a separate branch for the docker stuff

**Pull request closed without merging**
